config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	# 前台網址設計
  root "asbabs#index"
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end

  # 後台網址設計
  namespace :admin do
    root "asbabs#index"
    resources :products, except: [:show]
    resources :categories
    resources :posts, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	# 一個分類底下有很多產品
	has_many :products, dependent: :destroy

	# 資料驗證必輸入
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	# 很多評論會屬於一個文章
	belongs_to :post, optional: true

	# 很多評論會屬於某一個使用者
	belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
	# 文章圖片上載器
	mount_uploader :image, ImageUploader

	# 資料驗證必輸入
	validates :title, :description, presence: true

	# 一個文章會有很多評論
	has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	# 資料驗證必輸入
	validates :name, :tag, :description, :basic_price, :special_price , presence: true

	# 產品檔案下載器
	mount_uploader :image, PhotoUploader

	# 很多產品會屬於一個分類
	belongs_to :category, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # 一個使用者可以發表很多評論
	has_many :comments, dependent: :destroy
  
  def admin?
  	self.role == "admin"
  end
end

app/controllers/admin/asbabs_controller.rb
class Admin::AsbabsController < Admin::BaseController
	def index
		# 需要抓出 product.count 數量
		@products = Product.all

		# 需要抓出 post.count 數量
		@posts = Post.all

		# 需要抓出 user.count 數量
		@users = User.all
	end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

	before_action :find_post, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "文章建立成功"
			redirect_to admin_posts_path
		else
			flash.now[:alert] = "文章建立失敗"
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:notice] = "文章修改成功"
			redirect_to admin_posts_path
		else
			flash.now[:alert] = "文章修改失敗"
			render :edit
		end
	end

	def destroy
		@post.destroy
		flash[:alert] = "文章已被刪除"
		redirect_to admin_posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :description, :image)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	private

	def authenticate_admin
		unless current_user.admin?
			flash[:alert] = "您不具有管理員身份 !"
			redirect_to root_path
		end
	end
end

app/controllers/asbabs_controller.rb
class AsbabsController < ApplicationController
	def index
		# 首頁亂數秀出 4 個產品
		@products = Product.order("RANDOM()").limit(4)

		# 首頁秀出全部的分類
		@categories = Category.all

		# 首頁秀出最新文章
		@posts = Post.order("created_at DESC").limit(3)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
		# 找出特定的分類 Id
		@category = Category.find(params[:id])
		# 秀出同一分類下所有的產品
		@products = @category.products.all
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		# 首頁排序 新 => 舊
		@posts = Post.order("created_at DESC")

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end

	def show
		# 秀出特定的 Post 文章
		@post = Post.find(params[:id])

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all

		# show 頁面秀出最新文章
		@posts = Post.order("created_at DESC").limit(5)

		# 建立評論
		@comment = Comment.new
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		# 秀出特定產品的 Id
		@product = Product.find(params[:id])
		# 亂數秀出 Id 不是我的其它 4 個產品
		@products = Product.where.not(id: @product.id).order("RANDOM()").limit(4)
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end
end

app/helpers/admin/asbabs_helper.rb
module Admin::AsbabsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def verbose_data(data)
		data.strftime("%B %d, %Y")
	end
end

app/helpers/asbabs_helper.rb
module AsbabsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, post] do |f| %>
	<div class="row">
		<div class="col-12 col-md-12 col-xl-12">
			<!-- 錯誤訊息開始 -->
			<div class="error_message">
				<% if @post.errors.any? %>
				  <h2>We have some errors here !</h2>
				  <ul>
				    <% @post.errors.full_messages.each do |msg| %>
				      <li><%= msg %></li>
				    <% end %>
				  </ul>
				<% end %>
			</div>
			<!-- 錯誤訊息結束 -->
		</div>
		<div class="col-5 col-md-5 col-xl-5">
			<div class="form-group">
				<% if @post.image.blank? %>
					<%= image_tag "example_2" ,id: "target", class: "img-fluid" %>
				<% else %>
					<%= image_tag @post.image_url, class: "img-fluid", id: "target", original_url: @post.image_url %>
				<% end %>
			</div>
			<div class="form-group">
				<div class="custom-file">
					<%= f.label :image, "Image", class: "custom-file-label" %>
					<%= f.file_field :image, class: "custom-file-input" %>
				</div>
			</div>
		</div>
		<div class="col-7 col-md-7 col-xl-7">
			<div class="form-group">
				<%= f.label :title, "Title" %>
				<%= f.text_field :title, placeholder: "文章標題", class: "form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :description, "Description：" %>
				<%= f.text_area :description, rows: "15", class: "form-control" %>
			</div>
			<div class="form-group text-right mb-0">
				<%= f.submit class: "btn btn-success btn-lg" %>
			</div>
		</div>
	</div>
<% end %>

<script>
	$(function(){
		$("#post_image").change(function(){
			readURL(this, "target");
		});

		function readURL(input, image_tag_id){
			if(input.files && input.files[0]){
				var reader = new FileReader();
				reader.onload = function (e){
					$("#" + image_tag_id).attr('src', e.target.result);
				}
				reader.readAsDataURL(input.files[0]);
			} else {
				var original_url = $("#" + image_tag_id).attr("original_url");
				$("#" + image_tag_id).attr('src', original_url);
			}
		}
	});
</script>

app/views/admin/posts/_list_area.html.erb
<!-- 麵包屑區域開始 -->
<section class="list_area">
	<div class="container">
		<div class="list_area_block">
			<ul>
				<li>
					<%= link_to admin_posts_path do %>
						<i class="fas fa-sort-amount-up"></i>Posts
					<% end %>
				</li>
				<li>
					<%= link_to new_admin_post_path do %>
						<i class="fas fa-plus"></i>ADD Post
					<% end %>
				</li>
				<li><a href="#"><i class="fas fa-arrow-circle-down"></i>Export</a></li>
			</ul>
		</div>
	</div>
</section>
<!-- 麵包屑區域結束 -->

app/views/admin/posts/edit.html.erb
<!-- 後台導覽列開始 -->
<%= render "admin/shared/header_navbar" %>
<!-- 後台導覽列結束 -->

<!-- 麵包屑區域開始 -->
<%= render "list_area" %>
<!-- 麵包屑區域結束 -->

<!-- 表單開始 -->
<section class="post_form">
	<div class="container">
		<div class="post_form_area">
			<h2>edit data</h2>
			<%= render partial: "form", locals: {post: @post} %>
		</div>
	</div>
</section>
<!-- 表單結束 -->

app/views/admin/posts/index.html.erb
<!-- 後台導覽列開始 -->
<%= render "admin/shared/header_navbar" %>
<!-- 後台導覽列結束 -->

<!-- 麵包屑區域開始 -->
<%= render "list_area" %>
<!-- 麵包屑區域結束 -->

<!-- 訊息條區域開始 -->
<%= render "admin/shared/message" %>
<!-- 訊息條區域結束 -->

<!-- 總表區域開始 -->
<section class="post_table">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<h2>data table</h2>
				<div class="table_data table_rwd">
					<table class="table">
						<caption>List of Posts</caption>
						<thead>
							<tr>
								<th>Id</th>
								<th>Title</th>
								<th>狀態</th>
								<th></th>
							</tr>
						</thead>
						<% @posts.each do |post| %>
							<tbody>
								<tr class="item">
									<td><%= post.id %></td>
						      <td><%= post.title %></td>
						      <td>狀態</td>
						      <td class="text-center">
						      	<span class="publish">
						      		<a href="#" data_toggle="tooltip" title="發佈">
						      			<i class="fas fa-step-forward"></i>
						      		</a>
						      	</span>
						      	<span class="edit">
						      		<%= link_to edit_admin_post_path(post), data_toggle: "tooltip", title: "編輯" do %>
						      			<i class="fas fa-pencil-alt"></i>
						      		<% end %>
						      	</span>
						      	<span class="delete">
						      		<%= link_to admin_post_path(post), data_toggle: "tooltip", title: "刪除", method: :delete, data: {confirm:"Are you sure?"}  do %>
						      			<i class="fas fa-trash-alt"></i>
						      		<% end %>
						      	</span>
						      </td>
								</tr>
								<tr class="spacer"></tr>
							</tbody>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- 總表區域結束 -->

<script>
	$(function(){
		$('[data_toggle="tooltip"]').tooltip();
	});
</script>

app/views/admin/posts/new.html.erb
<!-- 後台導覽列開始 -->
<%= render "admin/shared/header_navbar" %>
<!-- 後台導覽列結束 -->

<!-- 麵包屑區域開始 -->
<%= render "list_area" %>
<!-- 麵包屑區域結束 -->

<!-- 表單開始 -->
<section class="post_form">
	<div class="container">
		<div class="post_form_area">
			<h2>new data</h2>
			<%= render partial: "form", locals: {post: @post} %>
		</div>
	</div>
</section>
<!-- 表單結束 -->

app/views/posts/_post_card.html.erb
<% @posts.each do |post| %>
	<div class="col-12 col-md-4 col-xl-4 mb_20">
		<div class="card post_block">
			<div class="post_image">
				<%= image_tag post.image.url, class: "card-img-top", alt: "Card image cap" %>
			</div>
			<div class="card-body">
				<h5 class="card-title"><%= post.title %></h5>
				<p class="card-text"><%= truncate(post.description, length: 130) %></p>
				<p class="read_more">
					<%= link_to "Read More...", post_path(post) %>
		    </p>
			</div>
			<div class="card-footer rwd_footer_size">
				<span class="post_author">
	      	<i class="fa fa-user"></i>By
	      	<b>Admin</b>
	      </span>
	      <span class="post_comment">
	      	<i class="far fa-comments"></i>
	      	<b>10 Comments</b>
	      </span>
			</div>
		</div>
	</div>
<% end %>

app/views/posts/_post_list.html.erb
<div class="post_right">
	<h4>Recent Blog</h4>
	<% @posts.each do |post| %>
		<div class="row">
			<div class="col-4 col-md-4 col-xl-4">
				<div class="left_image">
					<%= link_to post_path(post) do %>
						<%= image_tag post.image.url, class: "img-fluid" %>
					<% end %>
				</div>
			</div>
			<div class="col-8 col-md-8 col-xl-8">
				<div class="right_content">
					<p>
						<%= link_to truncate( post.title, length: 30), post_path(post) %>
					</p>
					<em><%= verbose_data post.created_at %></em>
				</div>
			</div>
		</div>
		<hr>
	<% end %>
</div>

app/views/posts/index.html.erb
<!-- 導覽區域開始 -->
<%= render "shared/head_nav" %>
<!-- 導覽區域結束 -->

<!-- 麵包屑區域開始 -->
<section class="breadcrumb d-none d-sm-block">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<ul class="breadcrumb_link">
					<li><%= link_to "Home", root_path, class: "link_item" %></li>
					<li>Blog</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<!-- 麵包屑區域結束 -->

<!-- 文章首頁區域開始 -->
<section class="post_index_area">
	<div class="container">
		<div class="row">
			<div class="col-8 col-md-8 col-xl-8">
				<div class="post_left">
					<h2>Blog</h2>
					<% @posts.each do |post| %>
						<div class="post_image">
							<%#= image_tag post.image.url, class: "img-fluid" %>
							<%= link_to post_path(post) do %>
								<%= image_tag post.image.url, class: "img-fluid" %>
							<% end %>
						</div>
						<h4><%= post.title %></h4>
						<div class="postmeta">
							<span class= "post_author">
								<i class="fa fa-user"></i>By
		      			<b>admin</b>
							</span>
							<span class= "post_date">
								<i class="far fa-calendar"></i>
								<b><%= verbose_data post.created_at %></b>
							</span>
							<span class= "post_comment">
								<i class="far fa-comments"></i>
		      			<b>10 comments</b>
							</span>
						</div>
						<div class="post_description">
							<p><%= simple_format(truncate post.description, length: 339 ) %></p>
						</div>
						<div class="read_more">
							<%= link_to "Read More...", post_path(post) %>
						</div>
					<% end %>
				</div>
			</div>
			<div class="col-4 col-md-4 col-xl-4">
				<%= render partial: "post_list", locals: {post: @posts} %>
			</div>
		</div>
	</div>
</section>
<!-- 文章首頁區域結束 -->

<!-- 頁腳區域開始 -->
<%= render "shared/footer" %>
<!-- 頁腳區域結束 -->

app/views/posts/show.html.erb
<!-- 導覽區域開始 -->
<%= render "shared/head_nav" %>
<!-- 導覽區域結束 -->

<!-- 麵包屑區域開始 -->
<section class="breadcrumb d-none d-sm-block">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<ul class="breadcrumb_link">
					<li><%= link_to "Home", root_path, class: "link_item" %></li>
					<li>Blog Detail</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<!-- 麵包屑區域結束 -->

<!-- 文章 show 區域開始 -->
<section class="post_show_area">
	<div class="container">
		<div class="row">
			<div class="col-8 col-md-8 col-xl-8">
				<div class="post_left">
					<h2>Blog Detail</h2>
					<div class="post_image">
						<%= image_tag @post.image.url, class: "img-fluid" %>
					</div>
					<h4><%= @post.title %></h4>
					<div class="postmeta">
						<span class= "post_author">
							<i class="fa fa-user"></i>By
	      			<b>admin</b>
						</span>
						<span class= "post_date">
							<i class="far fa-calendar"></i>
							<b><%= verbose_data @post.created_at %></b>
						</span>
						<span class= "post_comment">
							<i class="far fa-comments"></i>
	      			<b>10 comments</b>
						</span>
					</div>
					<div class="post_description">
						<p><%= simple_format @post.description %></p>
					</div>
					<div class="post_share">
						<span>share :</span>
						<ul>
							<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#"><i class="fab fa-github-alt"></i></a></li>
							<li><a href="#"><i class="fab fa-youtube"></i></a></li>
							<li><a href="#"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
					<hr>
					<div class="post_comment_block">
						<h3>Recent Comments</h3>
						<%= render partial: "comments/comment_block", locals: {comment: @comment} %>
						<%= render partial: "comments/comment_form", locals: {comment: @comment} %>
					</div>
				</div>
			</div>
			<div class="col-4 col-md-4 col-xl-4">
				<%= render partial: "post_list", locals: {post: @posts} %>
			</div>
		</div>
	</div>
</section>
<!-- 文章 show 區域結束 -->

<!-- 頁腳區域開始 -->
<%= render "shared/footer" %>
<!-- 頁腳區域結束 -->