config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	# 前台網址設計
  root "asbabs#index"
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end

  # 後台網址設計
  namespace :admin do
    root "asbabs#index"
    resources :products, except: [:show]
    resources :categories
    resources :posts, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	# 一個分類底下有很多產品
	has_many :products, dependent: :destroy

	# 資料驗證必輸入
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	# 很多評論會屬於一個文章
	belongs_to :post, optional: true

	# 很多評論會屬於某一個使用者
	belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
	# 文章圖片上載器
	mount_uploader :image, ImageUploader

	# 資料驗證必輸入
	validates :title, :description, presence: true

	# 一個文章會有很多評論
	has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	# 資料驗證必輸入
	validates :name, :tag, :description, :basic_price, :special_price , presence: true

	# 產品檔案下載器
	mount_uploader :image, PhotoUploader

	# 很多產品會屬於一個分類
	belongs_to :category, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # 一個使用者可以發表很多評論
	has_many :comments, dependent: :destroy
  
  def admin?
  	self.role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

	before_action :find_category, only: [:update, :destroy]

	def index
		@categories = Category.all
		
		if params[:id]
			find_category
		else 
			@category = Category.new
		end
	end

	def create
	  @category = Category.new(category_params)
	  if @category.save
	    flash[:notice] = "產品分類已成功建立!"
	    redirect_to admin_categories_path
	  else
	    @categories = Category.all
	    render :index
	  end
	end

	def update
		if @category.update(category_params)
			flash[:notice] = "產品分分類已修改成功!"
			redirect_to admin_categories_path
		else
			@categories = Category.all
			render :index
		end
	end

	def destroy
		@category.destroy
		flash[:notice] = "產品分分類已被刪除!"
		redirect_to admin_categories_path
	end

	private

	def category_params
	  params.require(:category).permit(:name)
	end

	def find_category
	  @category = Category.find(params[:id])
	end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

	before_action :find_post, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "文章建立成功"
			redirect_to admin_posts_path
		else
			flash.now[:alert] = "文章建立失敗"
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:notice] = "文章修改成功"
			redirect_to admin_posts_path
		else
			flash.now[:alert] = "文章修改失敗"
			render :edit
		end
	end

	def destroy
		@post.destroy
		flash[:alert] = "文章已被刪除"
		redirect_to admin_posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :description, :image)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	private

	def authenticate_admin
		unless current_user.admin?
			flash[:alert] = "您不具有管理員身份 !"
			redirect_to root_path
		end
	end
end

app/controllers/asbabs_controller.rb
class AsbabsController < ApplicationController
	def index
		# 首頁亂數秀出 4 個產品
		@products = Product.order("RANDOM()").limit(4)

		# 首頁秀出全部的分類
		@categories = Category.all

		# 首頁秀出最新文章
		@posts = Post.order("created_at DESC").limit(3)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
		# 找出特定的分類 Id
		@category = Category.find(params[:id])
		# 秀出同一分類下所有的產品
		@products = @category.products.all
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		# 首頁排序 新 => 舊
		@posts = Post.order("created_at DESC")

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end

	def show
		# 秀出特定的 Post 文章
		@post = Post.find(params[:id])

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all

		# show 頁面秀出最新文章
		@posts = Post.order("created_at DESC").limit(5)

		# 建立評論
		@comment = Comment.new
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		# 秀出特定產品的 Id
		@product = Product.find(params[:id])
		# 亂數秀出 Id 不是我的其它 4 個產品
		@products = Product.where.not(id: @product.id).order("RANDOM()").limit(4)
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end
end

app/helpers/admin/asbabs_helper.rb
module Admin::AsbabsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def verbose_data(data)
		data.strftime("%B %d, %Y")
	end
end

app/helpers/asbabs_helper.rb
module AsbabsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/categories/_list_area.html.erb
<!-- 麵包屑區域開始 -->
<section class="list_area">
	<div class="container">
		<div class="list_area_block">
			<ul>
				<li>
					<%= link_to admin_categories_path do %>
						<i class="fas fa-sort-amount-up"></i>Categories
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</section>
<!-- 麵包屑區域結束 -->

app/views/admin/categories/index.html.erb
<!-- 後台導覽列開始 -->
<%= render "admin/shared/header_navbar" %>
<!-- 後台導覽列結束 -->

<!-- 麵包屑區域開始 -->
<%= render "list_area" %>
<!-- 麵包屑區域結束 -->

<!-- 訊息條區域開始 -->
<%= render "admin/shared/message" %>
<!-- 訊息條區域結束 -->

<!-- 產品分類區域開始 -->
<section class="category_table">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<h2>data table</h2>
				<!-- 表單新增區域開始 -->
				<%= form_for [:admin, @category] do |f| %>
					<div class="form-inline">
						<div class="form-group">
							<%= f.text_field :name, placeholder: "Category name", class: "form-control" %>
						</div>
						<%= f.submit class: "btn btn-primary ml-1 mr-1" %>
					 	<% if @category.errors.any? %>
		        	<%= @category.errors.full_messages.to_sentence %>
		      	<% end %>
					</div>
				<% end %>
				<!-- 表單新增區域結束 -->
				<div class="table_data">
					<table class="table">
						<caption>List of Categories</caption>
						<thead>
							<tr>
								<th>Id</th>
								<th>Name</th>
								<th></th>
							</tr>
						</thead>
						<% @categories.each do |category| %>
							<tbody>
								<tr class="item">
									<td><%= category.id %></td>
					      	<td><%= category.name %></td>
					      	<td class="text-center">
						      	<span class="edit">
						      		<%= link_to admin_categories_path(id: category.id), data_toggle: "tooltip", title: "編輯" do %>
						      			<i class="fas fa-pencil-alt"></i>
						      		<% end %>
						      	</span>
						      	<span class="delete">
						      		<%= link_to admin_category_path(category), data_toggle: "tooltip", title: "刪除", method: :delete, data: {confirm:"Are you sure?"}  do %>
						      			<i class="fas fa-trash-alt"></i>
						      		<% end %>
						      	</span>
						      </td>
								</tr>
								<tr class="spacer"></tr>
							</tbody>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- 產品分類區域結束 -->

<script>
	$(function(){
		$('[data_toggle="tooltip"]').tooltip();
	});
</script>

app/views/categories/show.html.erb
<!-- 導覽區域開始 -->
<%= render "shared/head_nav" %>
<!-- 導覽區域結束 -->

<!-- 麵包屑區域開始 -->
<section class="breadcrumb d-none d-sm-block">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<ul class="breadcrumb_link">
					<li><%= link_to "Home", root_path, class: "link_item" %></li>
					<li><%= @category.name %></li>
				</ul>
			</div>
		</div>
	</div>
</section>
<!-- 麵包屑區域結束 -->

<!-- 同個分類下秀出全部產品開始 -->
<section class="category_products">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-3 col-xl-3">
				<div class="category_products_left">
					<div class="sidebar_shop">
						<h4>Shop Categories</h4>
						<ul>
							<% @categories.each do |category| %>
					      <li>
					      	<%= link_to category.name, category_path(category) %>
					      </li>
					    <% end %>
						</ul>
					</div>
					<div class="sidebar_tag">
						<h4>Popular Tag</h4>
						<ul>
							<li><a href="#" class="tag_btn">style</a></li>
							<li><a href="#" class="tag_btn">model</a></li>
							<li><a href="#" class="tag_btn">clothes</a></li>
							<li><a href="#" class="tag_btn">bikini</a></li>
							<li><a href="#" class="tag_btn">colorful</a></li>
							<li><a href="#" class="tag_btn">prom dresses</a></li>
							<li><a href="#" class="tag_btn mb_20">club dresses</a></li>
						</ul>	
					</div>
				</div>
			</div>
			<div class="col-12 col-md-9 col-xl-9">
				<div class="category_products_right">
					<div class="row">
						<div class="col-12 col-md-12 col-xl-12">
							<h2><%= @category.name %> <small><%= @category.products.count%> Products</small></h2>
						</div>
						<% @products.each do |product| %>
							<div class="col-6 col-md-4 col-xl-4">
								<%= render partial: "shared/product_list", locals: {product: product} %>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- 同個分類下秀出全部產品結束 -->

<!-- 頁腳區域開始 -->
<%= render "shared/footer" %>
<!-- 頁腳區域結束 -->