config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	# 前台網址設計
  root "asbabs#index"
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end

  # 後台網址設計
  namespace :admin do
    root "asbabs#index"
    resources :products, except: [:show]
    resources :categories
    resources :posts, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	# 一個分類底下有很多產品
	has_many :products, dependent: :destroy

	# 資料驗證必輸入
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	# 很多評論會屬於一個文章
	belongs_to :post, optional: true

	# 很多評論會屬於某一個使用者
	belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
	# 文章圖片上載器
	mount_uploader :image, ImageUploader

	# 資料驗證必輸入
	validates :title, :description, presence: true

	# 一個文章會有很多評論
	has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	# 資料驗證必輸入
	validates :name, :tag, :description, :basic_price, :special_price , presence: true

	# 產品檔案下載器
	mount_uploader :image, PhotoUploader

	# 很多產品會屬於一個分類
	belongs_to :category, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # 一個使用者可以發表很多評論
	has_many :comments, dependent: :destroy
  
  def admin?
  	self.role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

	before_action :find_post, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			flash[:notice] = "文章建立成功"
			redirect_to admin_posts_path
		else
			flash.now[:alert] = "文章建立失敗"
			render :new
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:notice] = "文章修改成功"
			redirect_to admin_posts_path
		else
			flash.now[:alert] = "文章修改失敗"
			render :edit
		end
	end

	def destroy
		@post.destroy
		flash[:alert] = "文章已被刪除"
		redirect_to admin_posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :description, :image)
	end

	def find_post
		@post = Post.find(params[:id])
	end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

	before_action :find_product, only: [:edit, :update, :destroy]

	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			flash[:notice] = "產品建立成功"
			redirect_to admin_products_path
		else
			flash.now[:alert] = "產品建立失敗"
			render :new
		end
	end

	def edit
	end

	def update
		if @product.update(product_params)
			flash[:notice] = "產品修改成功"
			redirect_to admin_products_path
		else
			flash.now[:alert] = "產品修改失敗"
			render :edit
		end
	end

	def destroy
		@product.destroy
		flash[:alert] = "產品已經被刪除 !"
		redirect_to admin_products_path
	end

	private

	def product_params
		params.require(:product).permit(:name, :tag, :description, :basic_price, :special_price, :image, :category_id)
	end

	def find_product
		@product = Product.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	private

	def authenticate_admin
		unless current_user.admin?
			flash[:alert] = "您不具有管理員身份 !"
			redirect_to root_path
		end
	end
end

app/controllers/asbabs_controller.rb
class AsbabsController < ApplicationController
	def index
		# 首頁亂數秀出 4 個產品
		@products = Product.order("RANDOM()").limit(4)

		# 首頁秀出全部的分類
		@categories = Category.all

		# 首頁秀出最新文章
		@posts = Post.order("created_at DESC").limit(3)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
		# 找出特定的分類 Id
		@category = Category.find(params[:id])
		# 秀出同一分類下所有的產品
		@products = @category.products.all
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		# 首頁排序 新 => 舊
		@posts = Post.order("created_at DESC")

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end

	def show
		# 秀出特定的 Post 文章
		@post = Post.find(params[:id])

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all

		# show 頁面秀出最新文章
		@posts = Post.order("created_at DESC").limit(5)

		# 建立評論
		@comment = Comment.new
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		# 秀出特定產品的 Id
		@product = Product.find(params[:id])
		# 亂數秀出 Id 不是我的其它 4 個產品
		@products = Product.where.not(id: @product.id).order("RANDOM()").limit(4)
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end
end

app/helpers/admin/asbabs_helper.rb
module Admin::AsbabsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def verbose_data(data)
		data.strftime("%B %d, %Y")
	end
end

app/helpers/asbabs_helper.rb
module AsbabsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<section class="product_form">
	<%= form_for [:admin, @product] do |f| %>
		<div class="container">
			<!-- 錯誤訊息開始 -->
			<div class="error_message">
				<% if @product.errors.any? %>
				  <h2>We have some errors here !</h2>
				  <ul>
				    <% @product.errors.full_messages.each do |msg| %>
				      <li><%= msg %></li>
				    <% end %>
				  </ul>
				<% end %>
			</div>
			<!-- 錯誤訊息結束 -->
			
			<!-- 表單區域開始 -->
			<div class="product_form_area">
				<div class="row">
					<div class="col-3 col-md-3 col-xl-3">
						<div class="form-group">
							<% if @product.image.blank? %>
								<%= image_tag "example_1" ,id: "target", class: "img-fluid" %>
							<% else %>
								<%= image_tag @product.image_url, class: "img-fluid", id: "target", original_url: @product.image_url %>
							<% end %>
						</div>
						<div class="form-group">
							<div class="custom-file">
								<%= f.label :image, "Image", class: "custom-file-label" %>
								<%= f.file_field :image, class: "custom-file-input" %>
							</div>
						</div>
					</div>
					<div class="col-9 col-md-9 col-xl-9">
						<div class="form-group">
							<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
						</div>
						<div class="row">
							<div class="col">
								<div class="form-group">
									<%= f.label :name, "Name：" %>
									<%= f.text_field :name, placeholder: "Name", class: "form-control" %>
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									<%= f.label :tag, "Tag：" %>
									<%= f.text_field :tag, placeholder: "Tag", class: "form-control" %>
								</div>
							</div>
						</div>
						<div class="form-group">
							<%= f.label :description, "Description：" %>
							<%= f.text_area :description, rows: "8", class: "form-control" %>
						</div>
						<div class="row">
							<div class="col">
								<div class="form-group">
									<%= f.label :basic_price, "原價：" %>
									<%= f.text_field :basic_price, placeholder: "基本定價", class: "form-control" %>
								</div>
							</div>
							<div class="col">
								<div class="form-group">
									<%= f.label :special_price, "特價：" %>
									<%= f.text_field :special_price, placeholder: "特別價錢", class: "form-control" %>
								</div>
							</div>
						</div>
						<div class="form-group text-right mb-0">
							<%= f.submit class: "btn btn-success btn-lg" %>
						</div>
					</div>
				</div>
			</div>
			<!-- 表單區域結束 -->
		</div>
	<% end %>
</section>

<script>
	$(function(){
		$("#product_image").change(function(){
			readURL(this, "target");
		});

		function readURL(input, image_tag_id){
			if(input.files && input.files[0]){
				var reader = new FileReader();
				reader.onload = function (e){
					$("#" + image_tag_id).attr('src', e.target.result);
				}
				reader.readAsDataURL(input.files[0]);
			} else {
				var original_url = $("#" + image_tag_id).attr("original_url");
				$("#" + image_tag_id).attr('src', original_url);
			}
		}
	});
</script>

app/views/admin/products/_list_area.html.erb
<!-- 麵包屑區域開始 -->
<section class="list_area">
	<div class="container">
		<div class="list_area_block">
			<ul>
				<li>
					<%= link_to admin_products_path do %>
						<i class="fas fa-sort-amount-up"></i>Products
					<% end %>
				</li>
				<li>
					<%= link_to new_admin_product_path do %>
						<i class="fas fa-plus"></i>ADD Product
					<% end %>
				</li>
				<li><a href="#"><i class="fas fa-arrow-circle-down"></i>Export</a></li>
			</ul>
		</div>
	</div>
</section>
<!-- 麵包屑區域結束 -->

app/views/admin/products/edit.html.erb
<!-- 後台導覽列開始 -->
<%= render "admin/shared/header_navbar" %>
<!-- 後台導覽列結束 -->

<!-- 麵包屑區域開始 -->
<%= render "list_area" %>
<!-- 麵包屑區域結束 -->

<!-- 表單開始 -->
<%= render "form" %>
<!-- 表單結束 -->

app/views/admin/products/index.html.erb
<!-- 後台導覽列開始 -->
<%= render "admin/shared/header_navbar" %>
<!-- 後台導覽列結束 -->

<!-- 麵包屑區域開始 -->
<%= render "list_area" %>
<!-- 麵包屑區域結束 -->

<!-- 訊息條區域開始 -->
<%= render "admin/shared/message" %>
<!-- 訊息條區域結束 -->

<!-- 總表區域開始 -->
<section class="product_table">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<h2>data table</h2>
				<div class="table_data table_rwd">
					<table class="table">
						<caption>List of Products</caption>
						<thead>
							<tr>
								<th>Id</th>
								<th>Name</th>
								<th>Category</th>
								<th>原價</th>
								<th>特價</th>
								<th>狀態</th>
								<th></th>
							</tr>
						</thead>
						<% @products.each do |product| %>
							<tbody>
								<tr class="item">
									<td><%= product.id %></td>
						      <td><%= product.name %></td>
						      <td><span class="product_category"><%= product.category.name %></span></td>
						      <td>$<%= product.basic_price %></td>
						      <td>$<%= product.special_price %></td>
						      <td>狀態</td>
						      <td class="text-center">
						      	<span class="publish">
						      		<a href="#" data_toggle="tooltip" title="發佈">
						      			<i class="fas fa-step-forward"></i>
						      		</a>
						      	</span>
						      	<span class="edit">
						      		<%= link_to edit_admin_product_path(product), data_toggle: "tooltip", title: "編輯" do %>
						      			<i class="fas fa-pencil-alt"></i>
						      		<% end %>
						      	</span>
						      	<span class="delete">
						      		<%= link_to admin_product_path(product), data_toggle: "tooltip", title: "刪除", method: :delete, data: {confirm:"Are you sure?"}  do %>
						      			<i class="fas fa-trash-alt"></i>
						      		<% end %>
						      	</span>
						      </td>
								</tr>
								<tr class="spacer"></tr>
							</tbody>
						<% end %>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- 總表區域結束 -->

<script>
	$(function(){
		$('[data_toggle="tooltip"]').tooltip();
	});
</script>

app/views/admin/products/new.html.erb
<!-- 後台導覽列開始 -->
<%= render "admin/shared/header_navbar" %>
<!-- 後台導覽列結束 -->

<!-- 麵包屑區域開始 -->
<%= render "list_area" %>
<!-- 麵包屑區域結束 -->

<!-- 表單開始 -->
<%= render "form" %>
<!-- 表單結束 -->

app/views/products/show.html.erb
<!-- 導覽區域開始 -->
<%= render "shared/head_nav" %>
<!-- 導覽區域結束 -->

<!-- 麵包屑區域開始 -->
<section class="breadcrumb d-none d-sm-block">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<ul class="breadcrumb_link">
					<li><%= link_to "Home", root_path, class: "link_item" %></li>
					<li><%= link_to @product.category.name, category_path(@product.category), class: "link_item" %></li>
					<li>Printed Round White T-shirt</li>
				</ul>
			</div>
		</div>
	</div>
</section>
<!-- 麵包屑區域結束 -->

<!-- 產品詳細介紹區域開始 -->
<section class="product_show_area">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-6 col-xl-6 mb_20">
				<div class="left_product_image">
					<%= image_tag @product.image.url, class: "img-fluid" %>
				</div>
			</div>
			<div class="col-12 col-md-6 col-xl-6 mb_20">
				<div class="right_product_content">
					<h2><%= @product.name %></h2>
					<div class="product_rating">
						<ul>
							<li><i class="fas fa-star"></i></li>
							<li><i class="fas fa-star"></i></li>
							<li><i class="fas fa-star"></i></li>
							<li><i class="fas fa-star"></i></li>
							<li><i class="fas fa-star"></i></li>
						</ul>
						<a href="#">2 reviews</a>
					</div>
					<div class="product_price">
						<del>$<%= @product.basic_price %></del>
						<span>$<%= @product.special_price %></span>
					</div>
					<div class="product_description">
						<p><%= simple_format @product.description %></p>
					</div>
					<div class="product_btn">
						<a href="#" class="button btn1">立即購買</a>
						<a href="#" class="button btn2">新增至購物車</a>
					</div>
					<div class="product_meta">
						<span>SKU : <span class="sku">Product SKU</span></span>
						<span>Category : <span class="category"><%= @product.category.name %></span></span>
						<span>Tag : <span class="tag"><%= @product.tag %></span></span>
					</div>
					<div class="product_share">
						<span>Share :</span>
						<ul>
	          	<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
	          	<li><a href="#"><i class="fab fa-twitter"></i></a></li>
	          	<li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
	          	<li><a href="#"><i class="fab fa-instagram"></i></a></li>
	          	<li><a href="#"><i class="fab fa-pinterest"></i></a></li>
            </ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- 產品詳細介紹區域結束 -->

<!-- 亂數產生產品區域開始 -->
<section class="random_product">
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-12 col-xl-12">
				<div class="random_product_title">
					<h2 class="text-center">Related Product</h2>
				</div>
			</div>
			<% @products.each do |product| %>
				<div class="col-6 col-md-3 col-xl-3">
					<%= render partial: "shared/product_list", locals: {product: product} %>
				</div>
			<% end %>
		</div>
	</div>
</section>
<!-- 亂數產生產品區域結束 -->

<!-- 頁腳區域開始 -->
<%= render "shared/footer" %>
<!-- 頁腳區域結束 -->