config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	# 前台網址設計
  root "asbabs#index"
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :posts, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end

  # 後台網址設計
  namespace :admin do
    root "asbabs#index"
    resources :products, except: [:show]
    resources :categories
    resources :posts, except: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	# 一個分類底下有很多產品
	has_many :products, dependent: :destroy

	# 資料驗證必輸入
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	# 很多評論會屬於一個文章
	belongs_to :post, optional: true

	# 很多評論會屬於某一個使用者
	belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
	# 文章圖片上載器
	mount_uploader :image, ImageUploader

	# 資料驗證必輸入
	validates :title, :description, presence: true

	# 一個文章會有很多評論
	has_many :comments, dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
	# 資料驗證必輸入
	validates :name, :tag, :description, :basic_price, :special_price , presence: true

	# 產品檔案下載器
	mount_uploader :image, PhotoUploader

	# 很多產品會屬於一個分類
	belongs_to :category, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # 一個使用者可以發表很多評論
	has_many :comments, dependent: :destroy
  
  def admin?
  	self.role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	private

	def authenticate_admin
		unless current_user.admin?
			flash[:alert] = "您不具有管理員身份 !"
			redirect_to root_path
		end
	end
end

app/controllers/asbabs_controller.rb
class AsbabsController < ApplicationController
	def index
		# 首頁亂數秀出 4 個產品
		@products = Product.order("RANDOM()").limit(4)

		# 首頁秀出全部的分類
		@categories = Category.all

		# 首頁秀出最新文章
		@posts = Post.order("created_at DESC").limit(3)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
		# 找出特定的分類 Id
		@category = Category.find(params[:id])
		# 秀出同一分類下所有的產品
		@products = @category.products.all
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :email, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		# 首頁排序 新 => 舊
		@posts = Post.order("created_at DESC")

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end

	def show
		# 秀出特定的 Post 文章
		@post = Post.find(params[:id])

		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all

		# show 頁面秀出最新文章
		@posts = Post.order("created_at DESC").limit(5)

		# 建立評論
		@comment = Comment.new
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		# 秀出特定產品的 Id
		@product = Product.find(params[:id])
		# 亂數秀出 Id 不是我的其它 4 個產品
		@products = Product.where.not(id: @product.id).order("RANDOM()").limit(4)
		# 配合導覽列需秀出全部的產品分類
		@categories = Category.all
	end
end

app/helpers/admin/asbabs_helper.rb
module Admin::AsbabsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def verbose_data(data)
		data.strftime("%B %d, %Y")
	end
end

app/helpers/asbabs_helper.rb
module AsbabsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/shared/_header_navbar.html.erb
<!-- 後台導覽列開始 -->
<header class=" header_area_admin sticky-top">
	<nav class="navbar navbar-expand-lg navbar-light">
		<%= link_to root_path do %>
			<%= image_tag "bapor_logo", class: "navbar-brand" %>
		<% end %>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    	<li class="nav-item">
	    		<%= link_to root_path, class: "nav-link basic" do %>
	        	BaporMarket<span class="sr-only">(current)</span>
	        <% end %>
	      </li>
	      <li class="nav-item">
	      	<%= link_to "Dashoard", admin_root_path, class: "nav-link basic" %>
	      </li>
	      <li class="nav-item">
	      	<%= link_to "Products", admin_products_path, class: "nav-link basic" %>
	      </li>
	      <li class="nav-item">
	        <%= link_to "Categories", admin_categories_path, class: "nav-link basic" %>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link basic" href="#">Orders</a>
	      </li>
	      <li class="nav-item">
	      	<%= link_to "Posts", admin_posts_path, class: "nav-link basic" %>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link basic" href="#">Users</a>
	      </li>
	    </ul>
	  </div>
	</nav>
</header>
<!-- 後台導覽列結束 -->

app/views/admin/shared/_message.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <strong><%= notice %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= alert %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asbab</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<!-- 頁腳區域開始 -->
<footer id="footer" class="footer">
	<div class="footer_top">
		<div class="footer_middle">
			<div class="container">
				<div class="row">
					<div class="col-12 col-md-6 col-lg-4 mb_sm_30">
						<div class="footer_block">
							<h6>What We Are?</h6>
							<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.</p>
						</div>
					</div>
					<div class="col-6 col-md-6 col-lg-2 mb-sm-40 d-none d-sm-block">
						<div class="footer_block">
							<h6>Information</h6>
							<ul class="list-none">
								<li><a href="#">Men</a></li>
								<li><a href="#">Women</a></li>
								<li><a href="#">Kids</a></li>
								<li><a href="#">Accessories</a></li>
								<li><a href="#">Brand</a></li>
								<li><a href="#">Blog</a></li>
							</ul>
						</div>
					</div>
					<div class="col-6 col-md-6 col-lg-2 mb_sm_30">
						<div class="footer_block">
							<h6>Usefull Links</h6>
							<ul class="list-none">
	              <li><a href="about.html">About Us</a></li>
	              <li><a href="#">Customer Service</a></li>
	              <li><a href="#">Privacy Policy</a></li>
	              <li><a href="#">Orders and Returns</a></li>
	              <li><a href="#">Help &amp; FAQs</a></li>
	              <li><a href="contact.html">Conatct Us</a></li>
	            </ul>
						</div>
					</div>
					<div class="col-6 col-md-6 col-lg-4 mb_sm_30">
						<div class="footer_block contactus_block">
							<h6>Conatct Us</h6>
							<p><i class="fa fa-map-marker" aria-hidden="true"></i>
                 Gelderseplein 750, 601 WZ Rotterdam,<br>
                 Netherlands              
              </p>
              <p>
              	<i class="fa fa-envelope" aria-hidden="true"></i>
              	<a href="mailto:vitata710@gmail.com">vitata710@gmail.com</a>
              </p>
              <p><i class="fa fa-phone" aria-hidden="true"></i>+0123-456-789</p>
              <p><i class="fa fa-fax" aria-hidden="true"></i>+0123-456-789</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="footer_bottom">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-6 col-xl-6">
					<p class="copyright">
						© Copyrights <a href="#" class="color" target="_blank">Bapor</a>. All Rights Reserved.
					</p>
				</div>
				<div class="col-12 col-md-6 col-xl-6">
					<div class="social_link">
						<ul>
							<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#"><i class="fab fa-github-alt"></i></a></li>
							<li><a href="#"><i class="fab fa-youtube"></i></a></li>
							<li><a href="#"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- 頁腳區域結束 -->

app/views/shared/_head_nav.html.erb
<!-- 導覽區域開始 -->
<header class="header_area">
	<div class="header_top">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12 col-md-4 col-xl-3">
					<div class="text-left header_top_left d-none d-sm-block">
						<p>Welcome to <b>BAPOR ~ You will love it.</b></p>
					</div>
				</div>
				<div class="col-12 col-md-8 col-xl-9">
					<div class="header_top_right">
						<% if current_user %>
							<!--登入之後 -->
							<a href="#"><i class="fa fa-shopping-basket"></i>購物車</a>
							<a href="#"><i class="fa fa-user"></i>我的帳戶</a>
							<%#= link_to '修改密碼', edit_user_registration_path %>
							<a href="#"><i class="fa fa-heart"></i>願望清單</a>
							<%= link_to destroy_user_session_path, method: :delete do %>
								<i class="fa fa-share-square"></i>會員登出
							<% end %>
    				<% else %>
    					<!--登入之前 -->
    					<%= link_to new_user_registration_path do %>
    						<i class="fa fa-user-plus"></i>註冊加入
    					<% end %>
    					<%= link_to new_user_session_path do %>
    						<i class="fa fa-hand-pointer"></i>會員登入
    					<% end %>
    				<% end %>
						<!--登入之後 -->
						<!-- <a href="#"><i class="fa fa-shopping-basket"></i>購物車</a> -->
						<!-- <a href="#"><i class="fa fa-user"></i>我的帳戶</a> -->
						<!-- <a href="#"><i class="fa fa-heart"></i>願望清單</a> -->
						<!-- <a href="#"><i class="fa fa-share-square"></i>會員登出</a> -->
						<!--登入之前 -->
						<!-- <a href="#"><i class="fa fa-user-plus"></i>註冊加入</a> -->
						<!-- <a href="#"><i class="fa fa-hand-pointer"></i>會員登入</a> -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="header_main">
		<nav class="navbar navbar-expand-lg navbar-light">
			<%= link_to root_path do %>
				<%= image_tag "bapor_logo" %>
			<% end %>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>

		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav ml-auto rwd_ul_bg">
		      <li class="nav-item">
		      	<%= link_to "Home", root_path, class: "nav-link nav_link_page" %>
		      </li>
		      <% @categories.each do |category| %>
			      <li class="nav-item">
			      	<%= link_to category.name, category_path(category), class: "nav-link nav_link_page" %>
			      </li>
			    <% end %>
		      <li class="nav-item">
		      	<%= link_to "Blog", posts_path, class: "nav-link nav_link_page" %>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link nav_link_page" href="#">Contact</a>
		      </li>
		    </ul>
		  </div>
		</nav>
	</div>
</header>
<!-- 導覽區域結束 -->

app/views/shared/_product_list.html.erb
<!-- 產品卡片區域開始 -->
<%= link_to product_path(product) do %>
	<div class="product_item">
		<div class="product_image_wraper">
			<%= image_tag product.image.url, class: "img-fluid big_img" %>
		</div>
		<div class="text-center product_content">
			<p><%= product.name %></p>
			<del>$<%= product.basic_price %></del>
			<span>$<%= product.special_price %></span>
		</div>
	</div>
<% end %>
<!-- 產品卡片區域結束 -->